accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('create/', views.UserCreateView.as_view(),name="create"),
    path('index/', views.IndexView.as_view(), name="index"),
    path('profile/<int:pk>/follow/', views.follow, name='follow'),
    path('profile/<int:pk>/block/', views.block, name='block'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('profile/<int:pk>/info/', views.Info.as_view(), name='info'),
    path('profile/<int:pk>/info/accept/', views.accept, name='accept'),
    path('profile/<int:pk>/info/reject/', views.reject, name='reject'),
]

app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'twitterclone'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('post_new/', views.post_new, name='post_new'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('delete/<int:post_id>/', views.delete, name='delete'),
    path('<postId>/like/', login_required(views.Likes.as_view()),name='like'),
]

config/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^friendship/', include('friendship.urls'))
]

templates/twitterclone/detail.html
{% extends "base.html" %}

{% load custom_filter %}

{% block content %}

<h1>detail page</h1>
<p>内容：{{ post.text }}</p>
<p>#{{ post.tag }}</p>
{% if user.is_authenticated %}
{% if post.author == login_user %}
<button><a href="{% url 'twitterclone:edit' post.pk %}">編集</a></button>
<button><a href="{% url 'twitterclone:delete' post.pk %}">削除</a></button>
{% endif %}

<div id="like">
<div class="like_posts_{{post.id}}">
    {{ post|is_like:login_user }}
    {{ like_posts|get_likes:post.id }}
</div>
</div>
{%  endif %}

<script>
    $(document).on('click', '.like', function () {
        var id = $(this).attr("id");
        do_like(id)
    });


    function do_like(post_id) {
        $.ajax({
                url: `../../${post_id}/like`,
                type: 'get'
            })
            .done((data) => {
                $('.like_posts_' + post_id).html(data);
            })
    }
</script>


{% endblock %}

templates/twitterclone/edit.html
{% extends 'base.html' %}

{% block content %}

<h1>edit page</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    {{ form.as_p }}
    <button type="submit">編集する</button>
</form>

{% endblock %}

templates/twitterclone/index.html
{% extends "base.html" %}

{% block content %}

{% if messages %}
{% for message in messages %}
<h3> {{ message }}</h3>
{% endfor %}
{% endif %}
{% if user.is_authenticated %}
<li><a href="{% url 'twitterclone:post_new' %}" class="act">Add Post</a></li>
{% endif %}

{% for post in post_list %}
<a href="{% url 'twitterclone:detail' post.pk %}">
    <p>{{post.text}}</p>
    <p>#{{post.tag}}</p>
    <p>{{post.published_date}}</p>
    <p>{{ post.like_num }}　いいね</p>
</a>
<p>by <a href="{% url 'accounts:profile' pk=post.author.id %}">{{post.author}}</a></p>
<hr>

{% endfor %}
{% endblock %}

templates/twitterclone/like.html

{#    <form action="{% url 'twitterclone:like' %}" method="POST">#}
{#        {% csrf_token %}#}
{#        {% if liked %}#}
{#        <button type="submit" id="like" name="post_id" value="{{post.id}}" class="btn"><i class="fas fa-lg fa-heart like-red"></i></button>#}
{#        {% else %}#}
{#        <button type="submit" id="like" name="post_id" value="{{post.id}}" class="btn"><i class="far fa-lg fa-heart"></i></button>#}
{#        {% endif %}#}
{#        <button type="submit" id="like" name="post_id" value="{{post.id}}" class="btn"><i class="fas fa-lg fa-heart like-red">a</i></button>#}
{#    </form>#}

{% load custom_filter %}
{{ post|is_like:user }}
{{ like_posts|get_likes:post.id }}

templates/twitterclone/post_new.html
{% extends 'base.html' %}

{% block content %}

<h1>Add page</h1>
<form action="{% url 'twitterclone:post_new' %}" enctype="multipart/form-data" method="POST">
 {% csrf_token %}
 {{ form.as_p }}
 <button type="submit">投稿する</button>
</form>

{% endblock %}