accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('create/', views.UserCreateView.as_view(),name="create"),
    path('index/', views.IndexView.as_view(), name="index"),
    path('profile/<int:pk>/follow/', views.follow, name='follow'),
    path('profile/<int:pk>/block/', views.block, name='block'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('profile/<int:pk>/info/', views.Info.as_view(), name='info'),
    path('profile/<int:pk>/info/accept/', views.accept, name='accept'),
    path('profile/<int:pk>/info/reject/', views.reject, name='reject'),
]

app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'twitterclone'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('post_new/', views.post_new, name='post_new'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('delete/<int:post_id>/', views.delete, name='delete'),
    path('<postId>/like/', login_required(views.Likes.as_view()),name='like'),
]

config/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^friendship/', include('friendship.urls'))
]

accounts/models.py
from django.db import models

accounts/forms.py
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import get_user_model

CustomUser = get_user_model()

class LoginForm(auth_forms.AuthenticationForm):
    def __init__(self, *args, **kw):
        super().__init__(*args, **kw)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label

accounts/views.py
import django.contrib.auth.models
from django.contrib.auth.views import LogoutView, LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView, ListView, DetailView, TemplateView
from django.urls import reverse_lazy
from . import forms
from app.models import Like, Post
from django.shortcuts import render, get_object_or_404
from friendship.models import Friend, Follow, Block, FriendshipRequest
import pdb
from django.views.decorators.http import require_POST, require_GET


class Login(LoginView):
    form_class = forms.LoginForm
    template_name = "accounts/login.html"


class Logout(LoginRequiredMixin, LogoutView):
    template_name = "accounts/logout.html"


class UserCreateView(CreateView):
    form_class = UserCreationForm
    template_name = "accounts/create.html"
    success_url = reverse_lazy('accounts:login')


class Profile(TemplateView):
    template_name = "accounts/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        display_user = get_object_or_404(django.contrib.auth.models.User, id=self.kwargs['pk'])
        posts = display_user.post_set.all().order_by('-published_date')
        like_posts = display_user.like_user.all()
        if self.request.user.is_authenticated:
            login_user = self.request.user
            friends = Friend.objects.are_friends(login_user, display_user)
            following = Follow.objects.following(login_user)
            blocking_user = Block.objects.is_blocked(login_user, display_user)
            try:
                requesting_follows = FriendshipRequest.objects.get(to_user=display_user.id, from_user=login_user.id)
            except:
                pass

        context['display_user'] = display_user
        context['posts'] = posts
        context['like_posts'] = like_posts
        if self.request.user.is_authenticated:
            context['login_user'] = login_user
            context['friends'] = friends
            context['following'] = following
            context['blocking_user'] = blocking_user
            try:
                context['requesting_follows'] = requesting_follows
            except:
                pass
        return context


@require_POST
def follow(request, pk):
    user = django.contrib.auth.models.User.objects.get(id=pk)
    if 'follow_req' in request.POST:
        Friend.objects.add_friend(request.user, user)
    if 'cancel_follow_req' in request.POST:
        friend_request = FriendshipRequest.objects.get(to_user=user.id)
        friend_request.cancel()
    if 'cancel_follow' in request.POST:
        Friend.objects.remove_friend(request.user, user)
    return render(request, 'accounts/follow.html', {'login_user': request.user})


@require_POST
def block(request, pk):
    other_user = django.contrib.auth.models.User.objects.get(id=pk)
    if 'block' in request.POST:
        Block.objects.add_block(request.user, other_user)
    if 'remove_block' in request.POST:
        Block.objects.remove_block(request.user, other_user)
    return render(request, 'accounts/block.html', {'login_user': request.user})


class Info(LoginRequiredMixin, TemplateView):
    template_name = "accounts/info.html"

    def get_context_data(self, **kwargs):
        user = get_object_or_404(django.contrib.auth.models.User, id=self.kwargs['pk'])
        login_user = self.request.user
        following = Follow.objects.following(user)
        followers = Follow.objects.followers(user)
        friends = Friend.objects.are_friends(login_user, user)
        blocking_user = Block.objects.is_blocked(login_user, user)
        requesting_follows = Friend.objects.sent_requests(user=user)
        requested_follows = Friend.objects.unread_requests(user=user)
        context = {
            'user': user,
            'login_user': login_user,
            'following': following,
            'followers': followers,
            'friends': friends,
            'blocking_user': blocking_user,
            'requesting_follows': requesting_follows,
            'requested_follows': requested_follows
        }
        return context


@require_POST
def accept(request, pk):
    user = django.contrib.auth.models.User.objects.get(id=pk)
    friend_request = FriendshipRequest.objects.get(from_user=pk, to_user=request.user.id)
    friend_request.accept()
    Follow.objects.add_follower(request.user, user)
    return render(request, 'accounts/accept.html', {'login_user': request.user})


@require_POST
def reject(request, pk):
    user = django.contrib.auth.models.User.objects.get(id=pk)
    friend_request = FriendshipRequest.objects.get(from_user=pk, to_user=request.user.id)
    friend_request.reject()
    Friend.objects.remove_friend(request.user, user)
    return render(request, 'accounts/reject.html', {'login_user': request.user})


class IndexView(ListView):
    model = django.contrib.auth.models.User
    template_name = "accounts/index.html"
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["login_user"] = self.request.user
        return context

templates/accounts/accept.html
{% extends 'base.html' %}
{% block content %}

処理は完了しました。
<p><a href="{% url 'twitterclone:index' %}">ホームへ戻る</a></p>

{% endblock %}

templates/accounts/block.html
{% extends 'base.html' %}
{% block content %}

処理は完了しました。
<p><a href="{% url 'twitterclone:index' %}">ホームへ戻る</a></p>

{% endblock %}

templates/accounts/create.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>CREATE</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<p>新規ユーザーの作成</p>
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">作成</button>
</form>
<p>既にアカウントをお持ちですか?? <a href="{% url 'accounts:login' %}">Login</a></p>
</body>
</html>

templates/accounts/follow.html
{% extends 'base.html' %}
{% block content %}

処理は完了しました。
<p><a href="{% url 'twitterclone:index' %}">ホームへ戻る</a></p>

{% endblock %}

templates/accounts/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Users</h1>

    {% for user in user_list %}
    <a href="{% url 'accounts:profile' pk=user.id %}">
       <p>{{user.username}}</p>
        <p>{{followings_count}}</p>
        <p>{{followers_count}}</p>
       <hr>
    </a>
    {% endfor %}
{% endblock %}

templates/accounts/info.html
{% extends "base.html" %}
{% block content %}
<h2>{{user.username}}</h2>
<a href="{% url 'accounts:profile' pk=user.id %}"><p>ユーザーページへ戻る</p></a>
<p>{% load friendshiptags %}</p>
<p>フォロー</p>
<ul>
    {% for following in followings %}
    <li>{{following}}</li>
    {% endfor %}
</ul>
<p>フォロワー</p>
{% for follower in followers %}
<li>{{follower}}</li>
{% endfor %}
{% if user == request.user %}
<p>フォロー申請中</p>
<ul>
    {% for requesting_follow in requesting_follows %}
    <li>{{requesting_follow.to_user}}</li>
    {% endfor %}
</ul>
<br>
<p>フォローリクエスト</p>
<ul>
    {% for requested_follow in requested_follows %}
    <li>{{requested_follow.from_user}}</li>
    <form action="{% url 'accounts:accept' pk=requested_follow.from_user.id %}" method="post">
        {% csrf_token %}
        <input type="submit" name="accept" value="accept">
    </form>
    <form action="{% url 'accounts:reject' pk=requested_follow.from_user.id %}" method="post">
        {% csrf_token %}
        <input type="submit" name="reject" value="reject">
    </form>
    {% endfor %}
</ul>
<br>
<p>ブロック中</p>
{% blocking user %}
{% endif %}

{% endblock %}

templates/accounts/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>LOGIN</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    {% if form.errors %}
      <p>ユーザー名またはパスワードが間違っています。もう一度入力してください。</p>
    {% endif %}

    {% if user.is_authenticated %}
        <p>Welcome, {{ user.username }}. </p>
    {% else %}
        <p>Welcome, new user. Please log in.</p>
    {% endif %}

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">ログイン</button>
    </form>
</body>
</html>

templates/accounts/logout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>LOGOUT</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<form action="{% url 'accounts:logout' %}" method="POST">
    {% csrf_token %}
    <button type="submit">ログアウト</button>
</form>
</body>
</html>

templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}

<h1 class="text-center my-5">{{ display_user.username }}のページ</h1>

{% if user.is_authenticated %}

{% if not display_user == login_user %}
<form action="{% url 'accounts:follow' pk=display_user.id %}" method="post">
    {% csrf_token %}
    {% if not display_user == requesting_follows.to_user %}
    <input type="submit" name="follow_req" value="フォローリクエスト">
    {% endif %}

    {% if display_user == requesting_follows.to_user %}
    <input type="submit" name="cancel_follow_req" value="フォローリクエスト取り消し">
    {% endif %}
    {% if display_user in following %}
    <input type="submit" name="cancel_follow" value="フォロー解除">
    {% endif %}
</form>

<form action="{% url 'accounts:block' pk=display_user.id %}" method="post">
    {% csrf_token %}
    {% if not blocking_user %}
    <input type="submit" name="block" value="ブロック">
    {% else %}
    <input type="submit" name="remove_block" value="ブロック解除">
    {% endif %}
</form>
{% endif %}

{% endif %}
<br>
<br>
<a href="{% url 'accounts:info' pk=display_user.id %}"><p>ユーザー詳細情報</p></a>


<p>お気に入りツイート</p>
<ul>
    {% for like_post in like_posts %}
    <a href="{% url 'twitterclone:detail' pk=like_post.post.id %}">
        <li>{{like_post.post}}</li>
    </a>
    {% endfor %}
</ul>

<p>自分のツイート</p>
{% for post in posts %}
<a href="{% url 'twitterclone:detail' pk=post.id %}">
    <div class="card m-4" style="min-width: 300px; max-height: 490px;">
        <div class="card-body">
            <p class="card-text">
                {{ post.text}}
            </p>
            <p>#{{post.tag}}</p>
            <p>{{post.created_at}}</p>
        </div>
    </div>
    {% endfor %}
</a>

{% endblock %}

templates/accounts/reject.html
{% extends 'base.html' %}
{% block content %}

処理は完了しました。
<p><a href="{% url 'twitterclone:index' %}">ホームへ戻る</a></p>

{% endblock %}