accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('create/', views.UserCreateView.as_view(),name="create"),
    path('index/', views.IndexView.as_view(), name="index"),
    path('profile/<int:pk>/follow/', views.follow, name='follow'),
    path('profile/<int:pk>/block/', views.block, name='block'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('profile/<int:pk>/info/', views.Info.as_view(), name='info'),
    path('profile/<int:pk>/info/accept/', views.accept, name='accept'),
    path('profile/<int:pk>/info/reject/', views.reject, name='reject'),
]

app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'twitterclone'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('post_new/', views.post_new, name='post_new'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('delete/<int:post_id>/', views.delete, name='delete'),
    path('<postId>/like/', login_required(views.Likes.as_view()),name='like'),
]

config/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^friendship/', include('friendship.urls'))
]

templates/base.html
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <title>{% if request.path != '/' %}{% block title %}{% endblock %} | {% endif %}twitterclone</title>
</head>
<body>
<div class="container">
    <header>
{#        <p class="site-name"><a href="{% url 'twitterclone:index' %}">Twitter Clone</a></p>#}
{#        <nav>#}
{#            <ul>#}
{#                {% if user.is_authenticated %}#}
{#                <li><a href="{% url 'accounts:logout' %}" class="logout">Logout</a></li>#}
{#                <li><a href="{% url 'accounts:profile' pk=login_user.id %}" class="profile">Profile</a></li>#}
{#                <li><a href="{% url 'accounts:index' %}" class="index">Users</a></li>#}
{#                {% else %}#}
{#                <li><a href="{% url 'accounts:create' %}" class="signup">Sign up</a></li>#}
{#                <li><a href="{% url 'accounts:login' %}" class="login">Login</a></li>#}
{#                {% endif %}#}
{#            </ul>#}
{#        </nav>#}
        <nav class="navbar navbar-dark bg-dark">
        <a href="{% url 'twitterclone:index' %}" class="navbar-brand">Twitterclone</a>
        <button class="navbar-toggler" type="button"
          data-toggle="collapse"
          data-target="#navmenu1"
          aria-controls="navmenu1"
          aria-expanded="false"
          aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navmenu1">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link logout" href="{% url 'accounts:logout' %}">logout</a>
            <a class="nav-item nav-link profile" href="{% url 'accounts:profile' pk=login_user.id %}">profile</a>
            <a class="nav-item nav-link index" href="{% url 'accounts:index' %}">Users</a>
          {% else %}
            <a class="nav-item nav-link signup" href="{% url 'accounts:create' %}">Sign up</a>
            <a class="nav-item nav-link login" href="{% url 'accounts:login' %}">Login</a>
          {% endif %}

        </div>
        </div>

          </div>
        </nav>
    </header>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</div>
</body>
</html>